#!/bin/bash
# Script to check what's using ports 80 and 8080

echo "=========================================="
echo "Checking Port 80..."
echo "=========================================="
echo ""
echo "Using lsof:"
sudo lsof -i :80 2>/dev/null || echo "No process found with lsof"
echo ""
echo "Using netstat:"
sudo netstat -tlnp | grep :80 || echo "No process found with netstat"
echo ""
echo "Using ss:"
sudo ss -tlnp | grep :80 || echo "No process found with ss"
echo ""

echo "=========================================="
echo "Checking Port 8080..."
echo "=========================================="
echo ""
echo "Using lsof:"
sudo lsof -i :8080 2>/dev/null || echo "No process found with lsof"
echo ""
echo "Using netstat:"
sudo netstat -tlnp | grep :8080 || echo "No process found with netstat"
echo ""
echo "Using ss:"
sudo ss -tlnp | grep :8080 || echo "No process found with ss"
echo ""

echo "=========================================="
echo "Checking Nginx Configuration..."
echo "=========================================="
echo ""
echo "Nginx config files:"
ls -la /etc/nginx/conf.d/ 2>/dev/null || echo "conf.d directory not found"
echo ""
echo "Nginx main config includes:"
sudo grep -E "include|listen" /etc/nginx/nginx.conf 2>/dev/null | head -10
echo ""

echo "=========================================="
echo "Checking Docker Containers..."
echo "=========================================="
echo ""
echo "Running containers and their ports:"
docker ps --format "table {{.Names}}\t{{.Ports}}" 2>/dev/null || echo "Docker not running or no containers"
echo ""

echo "=========================================="
echo "Checking Systemd Services..."
echo "=========================================="
echo ""
echo "Nginx service status:"
sudo systemctl status nginx --no-pager -l 2>/dev/null | head -10 || echo "Nginx service not found"
echo ""
echo "Apache/httpd service status:"
sudo systemctl status httpd --no-pager -l 2>/dev/null | head -5 || echo "Apache not installed/running"
echo ""

