services:
  backend:
    build:
      context: ./backend
    environment: # .env gitignored
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=mob-barley-db.c34y2w8we6eu.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USER=mob_user
      - DB_PASSWORD=Istanbul34
      - DB_NAME=mob_barley
      - DB_SSL=true
      - FRONTEND_BASE_URL=http://localhost:8080
    ports:
      - '3000:3000'
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - '8080:80'
    restart: always

