# This is the CD/CD pipeline
name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main", "intial-mvp" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test job (builds and tests FE+BE)
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installing a Node LTS version
      - name: Install Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22"

      # Installing the node modules for the frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Running lint check for the frontend
      - name: Run Frontend Lint
        working-directory: ./frontend
        run: npm run lint

      # Test that the frontend code build
      - name: Run Frontend Build
        working-directory: ./frontend
        run: npm run build

      # Running the frontend tests
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test:run

      # Installing the node modules for the backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Running the linter
      - name: Run Backend Lint
        working-directory: ./backend
        run: npm run lint

      # Running backend tests
      - name: Test Backend Code
        working-directory: ./backend
        run: npm run test

  # Build and push container images
  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      FRONTEND_IMAGE_NAME: 5g00dm04-3007/mobbarley-frontend
      BACKEND_IMAGE_NAME: 5g00dm04-3007/mobbarley-backend
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Frontend images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push Docker Backend images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}


